language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - stable
sudo: false
services:
  - mysql
before_install:
# use Travis CI default MySQL acount
  - export DB_HOST=localhost
  - export DB_USER=travis
  - export DB_PWD=''
